

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  ordertracking:
    build:
      context: .
      dockerfile: OrderTrackingItemCatalogService/Dockerfile
    container_name: ordertrackingitemcatalogservice
    ports:
      - "5001:5001"  
    depends_on:
      - rabbitmq  
    environment:
      RabbitMQ__Host: rabbitmq 
  