
services:
  order-tracking-item-catalog-service:
    build:
      context: .
      dockerfile: OrderTrackingItemCatalogService/Dockerfile
    ports:
      - "5001:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogConnection=Data Source=Catalog.db
    volumes:
      - ./Catalog.db:/app/Catalog.db 

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672" 
