

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  ordertracking:
    build:
      context: .
      dockerfile: OrderTrackingItemCatalogService/Dockerfile
    container_name: ordertrackingitemcatalogservice
    ports:
      - "5001:5001"  
    depends_on:
      - rabbitmq  
    environment:
      RabbitMQ__Host: rabbitmq 


  postgres:
    image: postgres:15-alpine  
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: identity        
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  